In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv("Fraud_Data.csv")
df

,Unnamed: 0,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,0,267,40,426708,2009-10-09,IL,250/500,500,1155.53,5000000,...,NO,5670,1260,630,3780,Ford,F150,1997,N,NaN
1,1,322,44,769602,2004-12-19,IL,100/300,1000,1156.19,0,...,?,49400,9880,4940,34580,Jeep,Wrangler,2010,N,NaN
2,2,259,45,608443,2006-12-21,IL,500/1000,2000,1175.07,0,...,NO,87780,7980,7980,71820,Honda,CRV,2011,N,NaN
3,3,446,61,259792,1999-04-07,IL,100/300,1000,1232.79,0,...,YES,70500,7050,14100,49350,Suburu,Forrestor,2007,N,NaN
4,4,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1724,1724,85,25,159768,2008-09-03,IN,250/500,500,1259.02,0,...,?,5640,940,940,3760,Nissan,Ultima,2005,N,NaN
1725,1725,131,33,432740,1990-10-09,IL,100/300,2000,1081.17,0,...,NO,4900,490,490,3920,Toyota,Camry,2010,N,NaN
1726,1726,194,35,275092,2012-03-14,IL,500/1000,500,1416.24,0,...,?,5940,1080,540,4320,Nissan,Pathfinder,2003,N,NaN
1727,1727,210,37,218684,2006-08-05,IN,500/1000,2000,1048.46,0,...,?,7080,1180,590,5310,Dodge,RAM,1999,N,NaN
1728,1728,86,28,613226,1991-08-22,IN,100/300,2000,1595.07,0,...,YES,70920,11820,11820,47280,Jeep,Wrangler,2002,N,NaN

In [ ]:
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder

# Load your dataset
df = pd.read_csv("Fraud_Data.csv")

# Replace NaN values with 'Unknown' in the authorities_contacted column
df['authorities_contacted'].fillna('Unknown', inplace=True)

df.to_csv('df_imputed.csv', index=True)